Add Ant Design page layout and components
pasankg/projectWukong pull request #1
Opened 2024-09-11 11:40 UTC by pasankg

![Screenshot 2024-09-11 at 9 42 08 PM](https://github.com/user-attachments/assets/32eafb1e-d385-4197-828e-00ca3879de26)

2024-09-11 12:51 UTC, ranidu commented on src/components/ResumeGenerator/Layout/Grid.tsx
> +  <>
Remove this empty fragment wrapper

2024-09-11 12:56 UTC, ranidu commented on src/App.tsx
> +      fullName={`${fileData?.nameCard?.fullName}`}
What is the purpose of using template literals here ? simply use 
`fullName={fileData?.nameCard?.fullName}`

2024-09-11 13:06 UTC, ranidu commented on src/components/ResumeGenerator/Sections/NameCardSection.tsx
> +import { nameCard } from "../../../types/index";
import statement should be as below
`import { nameCard } from '../../../types`

2024-09-11 13:19 UTC, ranidu requested changes
Please ensure the code is cleaned up before raising a PR

2024-09-11 13:19 UTC, ranidu commented on src/components/ResumeGenerator/Layout/PageLayout.tsx
> +} from "./index";
change this to 
`import {
  HeaderComponent,
  SidebarComponent,
  ContentComponent,
  FooterComponent,
} from "./";`

2024-09-11 13:19 UTC, ranidu commented on src/App.tsx
> +      contactDetails={`${fileData?.nameCard?.contactDetails}`}
The reason `nameCard?.contactDetails?.email` is not accessible in `NameCardComponent.tsx` is that you're trying to cast an object to a string. This makes the object inaccessible. 
Change it to `contactDetails={fileData?.nameCard?.contactDetails}`

2024-09-12 10:51 UTC, pasankg commented on src/App.tsx
> +      fullName={`${fileData?.nameCard?.fullName}`}
The syntax I had prints the values, but we don't need to print. Is that the reason ?

2024-09-12 10:52 UTC, pasankg commented on src/App.tsx
> +      contactDetails={`${fileData?.nameCard?.contactDetails}`}
Understood

2024-09-12 10:54 UTC, pasankg commented on src/components/ResumeGenerator/Layout/Grid.tsx
> +  <>
I thought I need to wrap the return with emtpy fragment. May be I'm confused with that practise. Because we are not returning anything here. Is that correct ?

2024-09-12 10:54 UTC, pasankg commented on src/components/ResumeGenerator/Layout/PageLayout.tsx
> +} from "./index";
Okay, because index file is called automatically.

2024-09-12 10:55 UTC, pasankg commented on src/components/ResumeGenerator/Sections/NameCardSection.tsx
> +import { nameCard } from "../../../types/index";
Done

2024-09-14 07:59 UTC, ranidu commented on src/components/ResumeGenerator/Sections/SocialSection.tsx
> +      {socialData.map((social, s) => {
change this to lodash map

2024-09-14 07:59 UTC, ranidu commented on src/components/ResumeGenerator/Sections/SocialSection.tsx
> +          <a key={s} href={social?.socialLink}>
please make sure to add meaningful names to variable

2024-09-14 07:59 UTC, ranidu commented on src/components/ResumeGenerator/Sections/SummarySection.tsx
> +      {profileSummaryData.map((item, i) => {
change this to lodash map

2024-09-14 07:59 UTC, ranidu commented on src/App.tsx
> +      <NameCardSection
since you're parsing all attributes this can be simplify to 
`<NameCardSection {...fileData?.namecard} />`

2024-09-14 07:59 UTC, ranidu commented on src/components/ResumeGenerator/Sections/SummarySection.tsx
> +        return <li key={i}>{parse(item)}</li>;
as a best practice don't use array index as key out of box. always use a key that uniquely identifies the element among its siblings. in this case u can create a string key `profile-summary-${index}`

2024-09-15 01:00 UTC, pasankg commented on src/App.tsx
> +      <NameCardSection
Ta

2024-09-15 01:13 UTC, pasankg commented on src/components/ResumeGenerator/Sections/SummarySection.tsx
> +      {profileSummaryData.map((item, i) => {
Added above

2024-09-21 02:28 UTC, pasankg commented
Moved to https://github.com/pasankg/projectWukong/pull/2

2024-09-21 02:28 UTC, closed without merging